In [275]:
import pandas as pd
pd.set_option("display.max_rows", None)

In [276]:
df = pd.read_csv("/Users/Yashwanth.B/jupyter/datasets/house_prices_train.csv")

In [277]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [278]:
df.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType        872
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
dtype: int64

In [279]:
df = df.drop(columns=["Alley", "PoolQC", "Fence", "MiscFeature"])

In [280]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [281]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
Street             0
LotShape           0
LandContour        0
Utilities          0
LotConfig          0
LandSlope          0
Neighborhood       0
Condition1         0
Condition2         0
BldgType           0
HouseStyle         0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
RoofStyle          0
RoofMatl           0
Exterior1st        0
Exterior2nd        0
MasVnrType       872
MasVnrArea         8
ExterQual          0
ExterCond          0
Foundation         0
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinSF1         0
BsmtFinType2      38
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
Heating            0
HeatingQC          0
CentralAir         0
Electrical         1
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
KitchenQual        0
TotRmsAbvGrd       0
Functional         0
Fireplaces         0
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageCars         0
GarageArea         0
GarageQual        81
GarageCond        81
PavedDrive         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
dtype: int64

MasVnrType
MasVnrArea
LotFrontage
BsmtQual
BsmtCond
BsmtExposure
BsmtFinType1
BsmtFinSF1
BsmtFinType2

In [282]:
df["MasVnrType"] = df["MasVnrType"].fillna(df["MasVnrType"].mode()[0])

In [283]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
Street             0
LotShape           0
LandContour        0
Utilities          0
LotConfig          0
LandSlope          0
Neighborhood       0
Condition1         0
Condition2         0
BldgType           0
HouseStyle         0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
RoofStyle          0
RoofMatl           0
Exterior1st        0
Exterior2nd        0
MasVnrType         0
MasVnrArea         8
ExterQual          0
ExterCond          0
Foundation         0
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinSF1         0
BsmtFinType2      38
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
Heating            0
HeatingQC          0
CentralAir         0
Electrical         1
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
KitchenQual        0
TotRmsAbvGrd       0
Functional         0
Fireplaces         0
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageCars         0
GarageArea         0
GarageQual        81
GarageCond        81
PavedDrive         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
dtype: int64

In [284]:
df["MasVnrArea"] = df["MasVnrArea"].fillna(df["MasVnrArea"].mode()[0])

In [285]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
Street             0
LotShape           0
LandContour        0
Utilities          0
LotConfig          0
LandSlope          0
Neighborhood       0
Condition1         0
Condition2         0
BldgType           0
HouseStyle         0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
RoofStyle          0
RoofMatl           0
Exterior1st        0
Exterior2nd        0
MasVnrType         0
MasVnrArea         0
ExterQual          0
ExterCond          0
Foundation         0
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinSF1         0
BsmtFinType2      38
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
Heating            0
HeatingQC          0
CentralAir         0
Electrical         1
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
KitchenQual        0
TotRmsAbvGrd       0
Functional         0
Fireplaces         0
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageCars         0
GarageArea         0
GarageQual        81
GarageCond        81
PavedDrive         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
dtype: int64

In [286]:
df["LotFrontage"] = df["LotFrontage"].fillna(df["LotFrontage"].mode()[0])

In [287]:
df["FireplaceQu"] = df["FireplaceQu"].fillna(df["FireplaceQu"].mode()[0])

In [288]:
df.isnull().sum()

Id                0
MSSubClass        0
MSZoning          0
LotFrontage       0
LotArea           0
Street            0
LotShape          0
LandContour       0
Utilities         0
LotConfig         0
LandSlope         0
Neighborhood      0
Condition1        0
Condition2        0
BldgType          0
HouseStyle        0
OverallQual       0
OverallCond       0
YearBuilt         0
YearRemodAdd      0
RoofStyle         0
RoofMatl          0
Exterior1st       0
Exterior2nd       0
MasVnrType        0
MasVnrArea        0
ExterQual         0
ExterCond         0
Foundation        0
BsmtQual         37
BsmtCond         37
BsmtExposure     38
BsmtFinType1     37
BsmtFinSF1        0
BsmtFinType2     38
BsmtFinSF2        0
BsmtUnfSF         0
TotalBsmtSF       0
Heating           0
HeatingQC         0
CentralAir        0
Electrical        1
1stFlrSF          0
2ndFlrSF          0
LowQualFinSF      0
GrLivArea         0
BsmtFullBath      0
BsmtHalfBath      0
FullBath          0
HalfBath          0
BedroomAbvGr      0
KitchenAbvGr      0
KitchenQual       0
TotRmsAbvGrd      0
Functional        0
Fireplaces        0
FireplaceQu       0
GarageType       81
GarageYrBlt      81
GarageFinish     81
GarageCars        0
GarageArea        0
GarageQual       81
GarageCond       81
PavedDrive        0
WoodDeckSF        0
OpenPorchSF       0
EnclosedPorch     0
3SsnPorch         0
ScreenPorch       0
PoolArea          0
MiscVal           0
MoSold            0
YrSold            0
SaleType          0
SaleCondition     0
SalePrice         0
dtype: int64

In [289]:
cols = [
    "Utilities", "BsmtQual", "BsmtCond", "BsmtExposure",
    "BsmtFinType1", "BsmtFinSF1", "BsmtFinType2",
    "FireplaceQu", "GarageType", "GarageYrBlt",
    "GarageFinish", "GarageCars", "GarageArea",
    "GarageQual", "GarageCond"
]

for col in cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [290]:
df.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       0
MasVnrArea       0
ExterQual        0
ExterCond        0
Foundation       0
BsmtQual         0
BsmtCond         0
BsmtExposure     0
BsmtFinType1     0
BsmtFinSF1       0
BsmtFinType2     0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
Heating          0
HeatingQC        0
CentralAir       0
Electrical       1
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
KitchenQual      0
TotRmsAbvGrd     0
Functional       0
Fireplaces       0
FireplaceQu      0
GarageType       0
GarageYrBlt      0
GarageFinish     0
GarageCars       0
GarageArea       0
GarageQual       0
GarageCond       0
PavedDrive       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
dtype: int64

In [291]:
df.dropna(inplace=True)

In [292]:
df.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       0
MasVnrArea       0
ExterQual        0
ExterCond        0
Foundation       0
BsmtQual         0
BsmtCond         0
BsmtExposure     0
BsmtFinType1     0
BsmtFinSF1       0
BsmtFinType2     0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
Heating          0
HeatingQC        0
CentralAir       0
Electrical       0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
KitchenQual      0
TotRmsAbvGrd     0
Functional       0
Fireplaces       0
FireplaceQu      0
GarageType       0
GarageYrBlt      0
GarageFinish     0
GarageCars       0
GarageArea       0
GarageQual       0
GarageCond       0
PavedDrive       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
dtype: int64

In [293]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [294]:
df.shape

(1459, 77)

In [295]:
categories = ["MSZoning", "Street","LotShape", "LandContour", "LotConfig", "LandSlope", "Neighborhood", "Condition1", "Condition2", "BldgType", 
              "HouseStyle", "Exterior1st", "MasVnrType", "ExterQual", "ExterCond", "Foundation", "BsmtQual", "BsmtCond", "BsmtExposure", 
              "BsmtFinType1", "BsmtFinType2", "Heating", "HeatingQC", "CentralAir", "Electrical", "KitchenQual", "Functional", "FireplaceQu",
              "GarageType", "GarageFinish", "GarageQual", "GarageCond", "PavedDrive",  "SaleType", "SaleCondition", "RoofMatl", 
              "RoofStyle", "Exterior2nd", 
             ]

In [296]:
for category in categories:
    splitted_category = pd.get_dummies(df[category], prefix=category)
    df = pd.concat([df, splitted_category], axis=1)
df = df.drop(columns=categories)

In [297]:
df.head()

,Id,MSSubClass,LotFrontage,LotArea,Utilities,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,...,Exterior2nd_HdBoard,Exterior2nd_ImStucc,Exterior2nd_MetalSd,Exterior2nd_Other,Exterior2nd_Plywood,Exterior2nd_Stone,Exterior2nd_Stucco,Exterior2nd_VinylSd,Exterior2nd_Wd Sdng,Exterior2nd_Wd Shng
0,1,60,65.0,8450,AllPub,7,5,2003,2003,196.0,...,False,False,False,False,False,False,False,True,False,False
1,2,20,80.0,9600,AllPub,6,8,1976,1976,0.0,...,False,False,True,False,False,False,False,False,False,False
2,3,60,68.0,11250,AllPub,7,5,2001,2002,162.0,...,False,False,False,False,False,False,False,True,False,False
3,4,70,60.0,9550,AllPub,7,5,1915,1970,0.0,...,False,False,False,False,False,False,False,False,False,True
4,5,60,84.0,14260,AllPub,8,5,2000,2000,350.0,...,False,False,False,False,False,False,False,True,False,False

In [298]:
df = df.drop(columns=["Id"])

In [299]:
df.to_csv("updated_house_prices.py")

In [300]:
splitted_rows = pd.get_dummies(df.Utilities)
df = pd.concat([df,splitted_rows], axis=1)
df = df.drop(columns=["Utilities"])

In [301]:
df.to_csv("updated_house_prices.py")

In [302]:
!pip install xgboost

Requirement already satisfied: xgboost in /Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages (3.2.0)
Requirement already satisfied: scipy in /Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages (from xgboost) (1.15.3)
Requirement already satisfied: numpy in /Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages (from xgboost) (2.2.6)

[notice] A new release of pip is available: 23.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [303]:
import xgboost

x = df.drop(columns=["SalePrice"])
y = df["SalePrice"]

classifier = xgboost.XGBRegressor()
classifier.fit(x, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [312]:
df.columns[df.columns.duplicated()]
print(df.iloc[0])

MSSubClass                   60
LotFrontage                65.0
LotArea                    8450
OverallQual                   7
OverallCond                   5
YearBuilt                  2003
YearRemodAdd               2003
MasVnrArea                196.0
BsmtFinSF1                  706
BsmtFinSF2                    0
BsmtUnfSF                   150
TotalBsmtSF                 856
1stFlrSF                    856
2ndFlrSF                    854
LowQualFinSF                  0
GrLivArea                  1710
BsmtFullBath                  1
BsmtHalfBath                  0
FullBath                      2
HalfBath                      1
BedroomAbvGr                  3
KitchenAbvGr                  1
TotRmsAbvGrd                  8
Fireplaces                    0
GarageYrBlt              2003.0
GarageCars                    2
GarageArea                  548
WoodDeckSF                    0
OpenPorchSF                  61
EnclosedPorch                 0
3SsnPorch                     0
ScreenPorch                   0
PoolArea                      0
MiscVal                       0
MoSold                        2
YrSold                     2008
SalePrice                208500
MSZoning_C (all)          False
MSZoning_FV               False
MSZoning_RH               False
MSZoning_RL                True
MSZoning_RM               False
Street_Grvl               False
Street_Pave                True
LotShape_IR1              False
LotShape_IR2              False
LotShape_IR3              False
LotShape_Reg               True
LandContour_Bnk           False
LandContour_HLS           False
LandContour_Low           False
LandContour_Lvl            True
LotConfig_Corner          False
LotConfig_CulDSac         False
LotConfig_FR2             False
LotConfig_FR3             False
LotConfig_Inside           True
LandSlope_Gtl              True
LandSlope_Mod             False
LandSlope_Sev             False
Neighborhood_Blmngtn      False
Neighborhood_Blueste      False
Neighborhood_BrDale       False
Neighborhood_BrkSide      False
Neighborhood_ClearCr      False
Neighborhood_CollgCr       True
Neighborhood_Crawfor      False
Neighborhood_Edwards      False
Neighborhood_Gilbert      False
Neighborhood_IDOTRR       False
Neighborhood_MeadowV      False
Neighborhood_Mitchel      False
Neighborhood_NAmes        False
Neighborhood_NPkVill      False
Neighborhood_NWAmes       False
Neighborhood_NoRidge      False
Neighborhood_NridgHt      False
Neighborhood_OldTown      False
Neighborhood_SWISU        False
Neighborhood_Sawyer       False
Neighborhood_SawyerW      False
Neighborhood_Somerst      False
Neighborhood_StoneBr      False
Neighborhood_Timber       False
Neighborhood_Veenker      False
Condition1_Artery         False
Condition1_Feedr          False
Condition1_Norm            True
Condition1_PosA           False
Condition1_PosN           False
Condition1_RRAe           False
Condition1_RRAn           False
Condition1_RRNe           False
Condition1_RRNn           False
Condition2_Artery         False
Condition2_Feedr          False
Condition2_Norm            True
Condition2_PosA           False
Condition2_PosN           False
Condition2_RRAe           False
Condition2_RRAn           False
Condition2_RRNn           False
BldgType_1Fam              True
BldgType_2fmCon           False
BldgType_Duplex           False
BldgType_Twnhs            False
BldgType_TwnhsE           False
HouseStyle_1.5Fin         False
HouseStyle_1.5Unf         False
HouseStyle_1Story         False
HouseStyle_2.5Fin         False
HouseStyle_2.5Unf         False
HouseStyle_2Story          True
HouseStyle_SFoyer         False
HouseStyle_SLvl           False
Exterior1st_AsbShng       False
Exterior1st_AsphShn       False
Exterior1st_BrkComm       False
Exterior1st_BrkFace       False
Exterior1st_CBlock        False
Exterior1st_CemntBd       False
Exterior1st_HdBoard       False
Exterior1st_ImStucc       False
Exterior1st_MetalSd       False
Exterior1st_Plywood       False
Exterior1st_Stone         False
Exterior1st_Stucco        False
Exterior1st_VinylSd        True
Exterior1st_Wd Sdng       False
Exterior1st_WdShing       False
MasVnrType_BrkCmn         False
MasVnrType_BrkFace         True
MasVnrType_Stone          False
ExterQual_Ex              False
ExterQual_Fa              False
ExterQual_Gd               True
ExterQual_TA              False
ExterCond_Ex              False
ExterCond_Fa              False
ExterCond_Gd              False
ExterCond_Po              False
ExterCond_TA               True
Foundation_BrkTil         False
Foundation_CBlock         False
Foundation_PConc           True
Foundation_Slab           False
Foundation_Stone          False
Foundation_Wood           False
BsmtQual_Ex               False
BsmtQual_Fa               False
BsmtQual_Gd                True
BsmtQual_TA               False
BsmtCond_Fa               False
BsmtCond_Gd               False
BsmtCond_Po               False
BsmtCond_TA                True
BsmtExposure_Av           False
BsmtExposure_Gd           False
BsmtExposure_Mn           False
BsmtExposure_No            True
BsmtFinType1_ALQ          False
BsmtFinType1_BLQ          False
BsmtFinType1_GLQ           True
BsmtFinType1_LwQ          False
BsmtFinType1_Rec          False
BsmtFinType1_Unf          False
BsmtFinType2_ALQ          False
BsmtFinType2_BLQ          False
BsmtFinType2_GLQ          False
BsmtFinType2_LwQ          False
BsmtFinType2_Rec          False
BsmtFinType2_Unf           True
Heating_Floor             False
Heating_GasA               True
Heating_GasW              False
Heating_Grav              False
Heating_OthW              False
Heating_Wall              False
HeatingQC_Ex               True
HeatingQC_Fa              False
HeatingQC_Gd              False
HeatingQC_Po              False
HeatingQC_TA              False
CentralAir_N              False
CentralAir_Y               True
Electrical_FuseA          False
Electrical_FuseF          False
Electrical_FuseP          False
Electrical_Mix            False
Electrical_SBrkr           True
KitchenQual_Ex            False
KitchenQual_Fa            False
KitchenQual_Gd             True
KitchenQual_TA            False
Functional_Maj1           False
Functional_Maj2           False
Functional_Min1           False
Functional_Min2           False
Functional_Mod            False
Functional_Sev            False
Functional_Typ             True
FireplaceQu_Ex            False
FireplaceQu_Fa            False
FireplaceQu_Gd             True
FireplaceQu_Po            False
FireplaceQu_TA            False
GarageType_2Types         False
GarageType_Attchd          True
GarageType_Basment        False
GarageType_BuiltIn        False
GarageType_CarPort        False
GarageType_Detchd         False
GarageFinish_Fin          False
GarageFinish_RFn           True
GarageFinish_Unf          False
GarageQual_Ex             False
GarageQual_Fa             False
GarageQual_Gd             False
GarageQual_Po             False
GarageQual_TA              True
GarageCond_Ex             False
GarageCond_Fa             False
GarageCond_Gd             False
GarageCond_Po             False
GarageCond_TA              True
PavedDrive_N              False
PavedDrive_P              False
PavedDrive_Y               True
SaleType_COD              False
SaleType_CWD              False
SaleType_Con              False
SaleType_ConLD            False
SaleType_ConLI            False
SaleType_ConLw            False
SaleType_New              False
SaleType_Oth              False
SaleType_WD                True
SaleCondition_Abnorml     False
SaleCondition_AdjLand     False
SaleCondition_Alloca      False
SaleCondition_Family      False
SaleCondition_Normal       True
SaleCondition_Partial     False
RoofMatl_ClyTile          False
RoofMatl_CompShg           True
RoofMatl_Membran          False
RoofMatl_Metal            False
RoofMatl_Roll             False
RoofMatl_Tar&Grv          False
RoofMatl_WdShake          False
RoofMatl_WdShngl          False
RoofStyle_Flat            False
RoofStyle_Gable            True
RoofStyle_Gambrel         False
RoofStyle_Hip             False
RoofStyle_Mansard         False
RoofStyle_Shed            False
Exterior2nd_AsbShng       False
Exterior2nd_AsphShn       False
Exterior2nd_Brk Cmn       False
Exterior2nd_BrkFace       False
Exterior2nd_CBlock        False
Exterior2nd_CmentBd       False
Exterior2nd_HdBoard       False
Exterior2nd_ImStucc       False
Exterior2nd_MetalSd       False
Exterior2nd_Other         False
Exterior2nd_Plywood       False
Exterior2nd_Stone         False
Exterior2nd_Stucco        False
Exterior2nd_VinylSd        True
Exterior2nd_Wd Sdng       False
Exterior2nd_Wd Shng       False
AllPub                     True
NoSeWa                    False
Name: 0, dtype: object

In [311]:
df1 = df.drop(columns=["SalePrice"])

classifier.predict(df1.iloc[[0]])

array([205311.19], dtype=float32)