## Logistics regression using HR columsn

In [39]:
import pandas as pd

In [40]:
df = pd.read_csv("/Users/Yashwanth.B/jupyter/datasets/HR_comma_sep.csv")
df.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [41]:
columns_top_drop = ["last_evaluation", "Work_accident"]
df = df.drop(columns=columns_top_drop)
df.head()

,satisfaction_level,number_project,average_montly_hours,time_spend_company,left,promotion_last_5years,Department,salary
0,0.38,2,157,3,1,0,sales,low
1,0.80,5,262,6,1,0,sales,medium
2,0.11,7,272,4,1,0,sales,medium
3,0.72,5,223,5,1,0,sales,low
4,0.37,2,159,3,1,0,sales,low

### Basic quantile outlier filter

In [42]:
quantile_filters = ["satisfaction_level", "average_montly_hours", "time_spend_company"]
for quantile_filter in quantile_filters:
    min_threshold = df[quantile_filter].quantile(0.05)
    max_threshold = df[quantile_filter].quantile(0.95)
    df = df[(df[quantile_filter] > min_threshold) & (df[quantile_filter] < max_threshold)]

In [43]:
df.shape

(8134, 8)

In [44]:
print(df["average_montly_hours"].skew())
print(df["satisfaction_level"].skew())

0.1859973306216951
-0.350986862465508

### hot encoding

In [45]:
categories = ["Department", "salary"]
for category in categories:
    splitted_categories = pd.get_dummies(df[category], prefix=category)
    df = pd.concat([df, splitted_categories], axis=1)
df = df.drop(columns=categories)
df.head()

,satisfaction_level,number_project,average_montly_hours,time_spend_company,left,promotion_last_5years,Department_IT,Department_RandD,Department_accounting,Department_hr,Department_management,Department_marketing,Department_product_mng,Department_sales,Department_support,Department_technical,salary_high,salary_low,salary_medium
0,0.38,2,157,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
3,0.72,5,223,5,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
4,0.37,2,159,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
5,0.41,2,153,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
7,0.92,5,259,5,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False

In [46]:
df

,satisfaction_level,number_project,average_montly_hours,time_spend_company,left,promotion_last_5years,Department_IT,Department_RandD,Department_accounting,Department_hr,Department_management,Department_marketing,Department_product_mng,Department_sales,Department_support,Department_technical,salary_high,salary_low,salary_medium
0,0.38,2,157,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
3,0.72,5,223,5,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
4,0.37,2,159,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
5,0.41,2,153,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
7,0.92,5,259,5,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14992,0.40,2,155,3,1,0,False,False,False,False,False,False,False,False,True,False,False,True,False
14994,0.40,2,151,3,1,0,False,False,False,False,False,False,False,False,True,False,False,True,False
14995,0.37,2,160,3,1,0,False,False,False,False,False,False,False,False,True,False,False,True,False
14996,0.37,2,143,3,1,0,False,False,False,False,False,False,False,False,True,False,False,True,False
14998,0.37,2,158,3,1,0,False,False,False,False,False,False,False,False,True,False,False,True,False

In [47]:
df.columns

Index(['satisfaction_level', 'number_project', 'average_montly_hours',
       'time_spend_company', 'left', 'promotion_last_5years', 'Department_IT',
       'Department_RandD', 'Department_accounting', 'Department_hr',
       'Department_management', 'Department_marketing',
       'Department_product_mng', 'Department_sales', 'Department_support',
       'Department_technical', 'salary_high', 'salary_low', 'salary_medium'],
      dtype='object')

In [48]:
df.head()

,satisfaction_level,number_project,average_montly_hours,time_spend_company,left,promotion_last_5years,Department_IT,Department_RandD,Department_accounting,Department_hr,Department_management,Department_marketing,Department_product_mng,Department_sales,Department_support,Department_technical,salary_high,salary_low,salary_medium
0,0.38,2,157,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
3,0.72,5,223,5,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
4,0.37,2,159,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
5,0.41,2,153,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
7,0.92,5,259,5,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False

In [49]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
x = df.drop(columns=['left'])
y = df['left']
model.fit(x, y)

/Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: divide by zero encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: overflow encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [52]:
df.columns

Index(['satisfaction_level', 'number_project', 'average_montly_hours',
       'time_spend_company', 'left', 'promotion_last_5years', 'Department_IT',
       'Department_RandD', 'Department_accounting', 'Department_hr',
       'Department_management', 'Department_marketing',
       'Department_product_mng', 'Department_sales', 'Department_support',
       'Department_technical', 'salary_high', 'salary_low', 'salary_medium'],
      dtype='object')

In [56]:
print(x.isnull().sum())

satisfaction_level        0
number_project            0
average_montly_hours      0
time_spend_company        0
promotion_last_5years     0
Department_IT             0
Department_RandD          0
Department_accounting     0
Department_hr             0
Department_management     0
Department_marketing      0
Department_product_mng    0
Department_sales          0
Department_support        0
Department_technical      0
salary_high               0
salary_low                0
salary_medium             0
dtype: int64

In [61]:
df.head()

,satisfaction_level,number_project,average_montly_hours,time_spend_company,left,promotion_last_5years,Department_IT,Department_RandD,Department_accounting,Department_hr,Department_management,Department_marketing,Department_product_mng,Department_sales,Department_support,Department_technical,salary_high,salary_low,salary_medium
0,0.38,2,157,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
3,0.72,5,223,5,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
4,0.37,2,159,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
5,0.41,2,153,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False
7,0.92,5,259,5,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False

In [62]:
df['predict_left'] = model.predict(df.drop(columns=['left']))

/Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

In [63]:
df.head()

,satisfaction_level,number_project,average_montly_hours,time_spend_company,left,promotion_last_5years,Department_IT,Department_RandD,Department_accounting,Department_hr,Department_management,Department_marketing,Department_product_mng,Department_sales,Department_support,Department_technical,salary_high,salary_low,salary_medium,predict_left
0,0.38,2,157,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False,1
3,0.72,5,223,5,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False,0
4,0.37,2,159,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False,1
5,0.41,2,153,3,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False,1
7,0.92,5,259,5,1,0,False,False,False,False,False,False,False,True,False,False,False,True,False,0

In [65]:
df.to_csv('predict_hr.csv', index=False)

### Evaluation

In [67]:
model.score(x, y)

/Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/Yashwanth.B/jupyter/jenv/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

0.8174329972953036